version: '3.8'
services:
  db:
    container_name: culturaeduca_db
    image: postgis/postgis:14-3.2-alpine
    restart: on-failure
    ports:
      - <DB_PORT>:5432
    environment:
      POSTGRES_DB: <DB_NAME>
      POSTGRES_USER: <DB_USERNAME>
      POSTGRES_PASSWORD: <DB_PASSWORD>
    volumes:
      - 'culturaeduca_db_data:/var/lib/postgresql/data'
  db_test:
    container_name: culturaeduca_db_test
    image: postgis/postgis:14-3.2-alpine
    restart: on-failure
    ports:
      - <DB_TEST_PORT>:5432
    environment:
      POSTGRES_DB: <DB_TEST_NAME>
      POSTGRES_USER: <DB_TEST_USERNAME>
      POSTGRES_PASSWORD: <DB_TEST_PASSWORD>
volumes:
  culturaeduca_db_data:
